### ISSUE TITLE
Parsing with heex grammar hangs with particular ranges

### ISSUE THREAD

**Issue by casouri** [tree-sitter/tree-sitter#3620]
### Problem

This is a bug that I encountered in Emacs and can reproduce with a standalone C program. If I use the heex grammar at [tree-sitter-heex](https://github.com/phoenixframework/tree-sitter-heex) to parse a particular file with particular ranges set to the parser, the parser hangs in an inf loop. I can reproduce with latest tree-sitter and tree-sitter-heex.

### Steps to reproduce

I created a reproduce repo, just run these commands:

```
git clone https://github.com/casouri/tree-sitter-heex-reproduce.git
cd tree-sitter-heex-reproduce
LD_LIBRARY_PATH=. sh run.sh
```

This should clone tree-sitter and tree-sitter-heex, build the reproduce program, and run it. You should see tree-sitter parser log keeps printing and printing.

I experimented a little bit with the bug, if I change the ranges, the bug disappears. That's all I know at this point.

Please let me know if anything is missing, and TIA!

### Expected behavior

The test program should terminate.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.23.0 (latest)

### Operating system/version

macOS 14.6.1 (23G93)

**Comment by sogaiu** [comment]
I was able to reproduce.

FWIW, I made the following tweaks to get things working here (possibly some / all of it has to do with local conditions (^^; ).

1. Make a symlink to libtree-sitter.so from libtree-sitter.so.0.23
2. Apply following diff to `run.sh`:

```diff
diff --git a/recipe b/recipe
index 90e051c..45f668b 100755
Binary files a/recipe and b/recipe differ
diff --git a/run.sh b/run.sh
index 92a69cd..384f9e3 100755
--- a/run.sh
+++ b/run.sh
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-EXT=dylib
+EXT=so
 
 git clone https://github.com/tree-sitter/tree-sitter.git --depth=1
-git clone git@github.com:casouri/tree-sitter-module.git --depth=1
+git clone https://github.com/casouri/tree-sitter-module.git --depth=1
 
 cd tree-sitter
 make
```
3. Start the shell script with `LD_LIBRARY_PATH=. sh run.sh`

**Comment by casouri** [comment]
Oops, I fixed the git url, the `EXT` actually doesn't matter, I forgot to delete it (^^;)

**Comment by ssbb** [comment]
Is it something in the tree-sitter core, or could it have been introduced by the tree-sitter-heex grammar?

**Comment by casouri** [comment]
Most likely something in the core. First of all, a grammar shouldn't be able to make tree-sitter core hang; also, I encountered the same issue with another grammar, markdown_inline, when I set a particular range to it. (Will post reproduce soon.)

**Comment by amaanq** [comment]
@casouri if you could try #3770 with the markdown_inline issue you encountered to see if that fixes it as well I'd be grateful

**Comment by casouri** [comment]
@amaanq Ah sorry, I totally forgot about uploading the repo! Anyway, I tried your branch and it fixed the markdown_inline hang too! Thank you so much! You're my hero ;-)

**Comment by ssbb** [comment]
Thank you, folks! You can’t imagine how happy I am that it’s fixed now. ❤️

**Comment by jasonmj** [comment]
I'm still seeing the issue running the v0.24.6 release. I checked for the fix in that release and more recent releases (as well as `main`) and I don't see the updated code from #3770 anywhere. Did the fix get reverted?

**Comment by clason** [comment]
Latest version is 0.25.3, please test that.

**Comment by jasonmj** [comment]
I was able to get as far as 0.25.1 with the version of tree-sitter built into the Emacs package on the nixos unstable channel and it appears to be fixed there too.
